language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - LARAVEL_VERSION=5.8.*
  - LARAVEL_VERSION=6.0.*

matrix:
  exclude:
    - php: 7.1
      env: LARAVEL_VERSION=6.0.*

services:
  - mysql

addons:
  mariadb: '10.3'

before_install:
  - mkdir xsir
  - shopt -s extglob
  - mv !(xsir) xsir
  - mv .git xsir
  - composer self-update

before_script:
  - mysql -e "CREATE DATABASE laravel;"
  - composer create-project --prefer-dist laravel/laravel laravel $LARAVEL_VERSION
  - mv .env.travis laravel/.env
  - mv xsir/phpunit.travis.xml laravel/phpunit.xml
  - cd laravel
  - composer config repositories.packages path ../xsir/.
  - composer require ximdex/semantic-information-repository "*"
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit

notifications:
  email:
    recipients:
      - travis@ximdex.com
    on_success: change
    on_failure: always
  slack:
    rooms:
      - ximdexteam:tJAT66V6VSJeHR3H2CDCImnK#travis-ci
